# Generated by Django 3.0.3 on 2020-02-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_page_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='alias',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
